[features]
resolution = true
skip-lint = false

[programs.localnet]
chat_protocol = "TfoKjohya9Ak5N1WrCoKCqaEbCq2EhucHWprbxqrYmV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"
#wallet = "usb://ledger?key=0"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
